### PR TITLE
Removed BitBodyProps

### PR DESCRIPTION
**Pull request by Kenoshen**
Completely removed BitBodyProps since it was just a state object within another state object (BitBody).  This was a major enough commit that I thought I might just want to do a PR for it now.

### CODE REVIEW

**Comment by MondayHopscotch** [comment]
I did this to keep bodies separated from their properties in the case that we wanted to allow ourselves to change things on the fly. The idea being that we can just strap various property objects to a body and change the behavior without having to rebuild the body.

Thoughts? (I'm open to this change, just seeing if my reasoning changes your thoughts at all)

**Comment by Kenoshen** [comment]
I see your point. But it seemed like there were properties in body props that shouldn't be separate of the actual body, like velocity. I'd say let's try and focus on keeping it simple and make it work really good and then build it up from there. I'm definitely not against the idea though.

**Comment by MondayHopscotch** [comment]
Sounds good. It won't be hard to go down a route like this later if we decide to. SO IT SHALL BE!
 :+1:

**Comment by MondayHopscotch** [comment]
One question I have -- should we merge my SAT changes first (the collision rework)? I don't think I hit too much on the bitbodyproperties class -- but my guess is that it will be easier to merge this into that rather than the other way around.

**Pull request merged**
